version: '3'
services:

  app:
    image: quay.io/keycloak/keycloak:12.0.4
    container_name: keycloak
    command: ["-Dkeycloak.profile.feature.upload_scripts=enabled"]
    environment:
      - KEYCLOAK_IMPORT=/tmp/realm-demo.json
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - ./keycloak/mytheme:/opt/jboss/keycloak/themes/mytheme
      - ./keycloak/realm-demo.json:/tmp/realm-demo.json
    ports: 
      - 8080:8080
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: keycloak_postgres
    restart: always
    tty: true
    ports:
      - 55432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root